#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ozelgunmesajlaricom.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db05082020")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMesaj(Mesaj instance);
    partial void UpdateMesaj(Mesaj instance);
    partial void DeleteMesaj(Mesaj instance);
    partial void InsertMesajTipi(MesajTipi instance);
    partial void UpdateMesajTipi(MesajTipi instance);
    partial void DeleteMesajTipi(MesajTipi instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db05082020ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Mesaj> Mesajs
		{
			get
			{
				return this.GetTable<Mesaj>();
			}
		}
		
		public System.Data.Linq.Table<MesajTipi> MesajTipis
		{
			get
			{
				return this.GetTable<MesajTipi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mesaj")]
	public partial class Mesaj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iKodMesaj;
		
		private System.Nullable<int> _iKodMesajTipi;
		
		private string _cMesaj;
		
		private System.Nullable<int> _iAktifMi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniKodMesajChanging(int value);
    partial void OniKodMesajChanged();
    partial void OniKodMesajTipiChanging(System.Nullable<int> value);
    partial void OniKodMesajTipiChanged();
    partial void OncMesajChanging(string value);
    partial void OncMesajChanged();
    partial void OniAktifMiChanging(System.Nullable<int> value);
    partial void OniAktifMiChanged();
    #endregion
		
		public Mesaj()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iKodMesaj", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iKodMesaj
		{
			get
			{
				return this._iKodMesaj;
			}
			set
			{
				if ((this._iKodMesaj != value))
				{
					this.OniKodMesajChanging(value);
					this.SendPropertyChanging();
					this._iKodMesaj = value;
					this.SendPropertyChanged("iKodMesaj");
					this.OniKodMesajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iKodMesajTipi", DbType="Int")]
		public System.Nullable<int> iKodMesajTipi
		{
			get
			{
				return this._iKodMesajTipi;
			}
			set
			{
				if ((this._iKodMesajTipi != value))
				{
					this.OniKodMesajTipiChanging(value);
					this.SendPropertyChanging();
					this._iKodMesajTipi = value;
					this.SendPropertyChanged("iKodMesajTipi");
					this.OniKodMesajTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMesaj", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string cMesaj
		{
			get
			{
				return this._cMesaj;
			}
			set
			{
				if ((this._cMesaj != value))
				{
					this.OncMesajChanging(value);
					this.SendPropertyChanging();
					this._cMesaj = value;
					this.SendPropertyChanged("cMesaj");
					this.OncMesajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iAktifMi", DbType="Int")]
		public System.Nullable<int> iAktifMi
		{
			get
			{
				return this._iAktifMi;
			}
			set
			{
				if ((this._iAktifMi != value))
				{
					this.OniAktifMiChanging(value);
					this.SendPropertyChanging();
					this._iAktifMi = value;
					this.SendPropertyChanged("iAktifMi");
					this.OniAktifMiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MesajTipi")]
	public partial class MesajTipi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iKodMesajTipi;
		
		private string _cAdi;
		
		private string _cSeo;
		
		private System.Nullable<int> _iAktifMi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniKodMesajTipiChanging(int value);
    partial void OniKodMesajTipiChanged();
    partial void OncAdiChanging(string value);
    partial void OncAdiChanged();
    partial void OncSeoChanging(string value);
    partial void OncSeoChanged();
    partial void OniAktifMiChanging(System.Nullable<int> value);
    partial void OniAktifMiChanged();
    #endregion
		
		public MesajTipi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iKodMesajTipi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iKodMesajTipi
		{
			get
			{
				return this._iKodMesajTipi;
			}
			set
			{
				if ((this._iKodMesajTipi != value))
				{
					this.OniKodMesajTipiChanging(value);
					this.SendPropertyChanging();
					this._iKodMesajTipi = value;
					this.SendPropertyChanged("iKodMesajTipi");
					this.OniKodMesajTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAdi", DbType="NVarChar(50)")]
		public string cAdi
		{
			get
			{
				return this._cAdi;
			}
			set
			{
				if ((this._cAdi != value))
				{
					this.OncAdiChanging(value);
					this.SendPropertyChanging();
					this._cAdi = value;
					this.SendPropertyChanged("cAdi");
					this.OncAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSeo", DbType="NVarChar(50)")]
		public string cSeo
		{
			get
			{
				return this._cSeo;
			}
			set
			{
				if ((this._cSeo != value))
				{
					this.OncSeoChanging(value);
					this.SendPropertyChanging();
					this._cSeo = value;
					this.SendPropertyChanged("cSeo");
					this.OncSeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iAktifMi", DbType="Int")]
		public System.Nullable<int> iAktifMi
		{
			get
			{
				return this._iAktifMi;
			}
			set
			{
				if ((this._iAktifMi != value))
				{
					this.OniAktifMiChanging(value);
					this.SendPropertyChanging();
					this._iAktifMi = value;
					this.SendPropertyChanged("iAktifMi");
					this.OniAktifMiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
